spring:
   application:
      name: currency-cloud-config-server
   cloud:
      config:
         server:
            git:
               uri: https://github.com/sachin19927/CurrencyExchangerMicroservice.git
#               skip-ssl-validation: true             
# username: sachin19927
         
server:
   port: 8888
   