spring:
   application:
      name: eureka-naming-server
   cloud:
      config:
         enabled: false 
server:
   port: 8761
   
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
   
