spring:
   application:
      name: api-gateway-micro-service
   cloud:
      config:
         enabled: false
      gateway:
         discovery:
            locator:
               enabled: true
               lowerCaseServiceId: true 

server:
   port: 8765

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
   instance:
      instance-id: ${spring.application.name}:${random.uuid}
